[package]
name = "web-optimizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = {version = "0.7.5", features = ["multipart"] }
load_image = "3.1.6"
tokio = { version = "1.39.2", features = ["full"] }
webp = "0.3.0"
zip = "2.1.6"
